import Head from "next/head";
import { useUser } from "@auth0/nextjs-auth0/client";
import { withPageAuthRequired as withPageAuthRequiredCSR } from "@auth0/nextjs-auth0/client";
import { withPageAuthRequired as withPageAuthRequiredSSR } from "@auth0/nextjs-auth0";
import { Button, Modal, Typography } from "@/components";
import { useRef } from "react";
import { AddBookModal } from "@/views/Books";

export default withPageAuthRequiredCSR(function Home() {
  const modalRef = useRef<{ open: () => void }>();

  return (
    <>
      <Head>
        <title>Nextjs learn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="p-5">
        <div className="flex justify-between">
          <Typography as="h1">Книги</Typography>
          <Button
            label="Добавить книгу"
            onClick={() => {
              modalRef.current?.open();
            }}
          />
        </div>
      </section>
      <AddBookModal ref={modalRef} />
    </>
  );
});

export const getServerSideProps = withPageAuthRequiredSSR();
