import Head from "next/head";
import { withPageAuthRequired as withPageAuthRequiredCSR } from "@auth0/nextjs-auth0/client";
import { withPageAuthRequired as withPageAuthRequiredSSR } from "@auth0/nextjs-auth0";
import { Button, ShowList, Typography } from "@/components";
import { useRef } from "react";
import { AddBookModal, BookCard } from "@/views/Books";
import { prisma } from "@/prisma";
import { Book } from "@prisma/client";
import { GetServerSideProps } from "next";

interface Props {
  books: Book[]
}


export default withPageAuthRequiredCSR(function Home({ books }: Props) {
  const modalRef = useRef<{ open: () => void }>();

  return (
    <>
      <Head>
        <title>Nextjs learn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="p-5">
        <div className="flex justify-between">
          <Typography as="h1">Книги</Typography>
          <Button
            label="Добавить книгу"
            onClick={() => {
              modalRef.current?.open();
            }}
          />
        </div>
        <div className="grid grid-cols-3 gap-5">
          <ShowList list={books}>
            {book => <BookCard {...book} key={book.id} />}
          </ShowList>
        </div>
      </section>
      <AddBookModal ref={modalRef} />
    </>
  );
});

export const getServerSideProps: GetServerSideProps = async () => {
  withPageAuthRequiredSSR();

  const books = await prisma.book.findMany();
  return {
    props: {
      books,
    },
  };
};
